spring.application.name=demo

messages.search.ignore-case=true
messages.search.min-length=0
messages.validation.min-context-length=5
messages.validation.max-context-length=500
messages.validation.require-author=true